export const GET_WORLD_STATS_REQUEST = 'GET_WORLD_STATS_REQUEST';
export const GET_WORLD_STATS_SUCCESS = 'GET_WORLD_STATS_SUCCESS';
export const GET_WORLD_STATS_FAILURE = 'GET_WORLD_STATS_FAILURE';
export const GET_COUNTRIES_STATS_REQUEST = 'GET_COUNTRIES_STATS_REQUEST';
export const GET_COUNTRIES_STATS_SUCCESS = 'GET_COUNTRIES_STATS_SUCCESS';
export const GET_COUNTRIES_STATS_FAILURE = 'GET_COUNTRIES_STATS_FAILURE';
